import api from "./api";
import type {
  AISuggestionInput,
  AISuggestionPlan,
  AISuggestionResponse,
  AllocatedEquipmentItem,
  AllocatedHumanItem,
  AllocatedLandItem,
  ConstraintReport,
  FitnessBreakdown,
  TimelinePhaseItem,
} from "../types/aiSuggestion";

export interface OptimizationSettings {
  populationSize?: number;
  generationCount?: number;
  mutationRate?: number;
  initialMutationRate?: number;
  finalMutationRate?: number;
  crossoverRate?: number;
  eliteCount?: number;
  tournamentSize?: number;
  topSuggestionCount?: number;
  maxScheduleShiftDays?: number;
  landWeight?: number;
  humanWeight?: number;
  equipmentWeight?: number;
  scheduleWeight?: number;
  penaltyWeight?: number;
  bonusWeight?: number;
  hardConstraintPenalty?: number;
  softConstraintPenalty?: number;
}

export const DEFAULT_OPTIMIZATION_SETTINGS: OptimizationSettings = {
  populationSize: 100,
  generationCount: 80,
  mutationRate: 0.15,
  initialMutationRate: 0.3,
  finalMutationRate: 0.05,
  crossoverRate: 0.8,
  eliteCount: 10,
  tournamentSize: 5,
  topSuggestionCount: 5,
  maxScheduleShiftDays: 7,
  landWeight: 25,
  humanWeight: 25,
  equipmentWeight: 25,
  scheduleWeight: 25,
  penaltyWeight: 1.0,
  bonusWeight: 1.0,
  hardConstraintPenalty: 40,
  softConstraintPenalty: 8,
};

export interface ApiOptimizationSuggestion {
  rank?: number;
  fitnessScore?: number;
  penaltyScore?: number;
  bonusScore?: number;
  fitnessBreakdown?: FitnessBreakdown;
  constraintReport?: ConstraintReport;
  conflictCount?: number;
  estimatedCompletionTime?: string;
  allocatedLands?: AllocatedLandItem[];
  allocatedHumans?: AllocatedHumanItem[];
  allocatedEquipment?: AllocatedEquipmentItem[];
  timeline?: TimelinePhaseItem[];
  advantages?: string[];
  disadvantages?: string[];
}

/**
 * Formats ISO date or raw date string to DD/MM/YYYY
 */
function formatDateShort(dateStr?: string | null): string {
  if (!dateStr) return "-";
  const date = new Date(dateStr);
  if (Number.isNaN(date.getTime())) return dateStr;
  return new Intl.DateTimeFormat("vi-VN", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  }).format(date);
}

/**
 * Calculates date difference in days
 */
function calculateDiffDays(startDateStr: string, endDateStr: string): number {
  const start = new Date(startDateStr);
  const end = new Date(endDateStr);
  if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) return 30;
  const diffTime = Math.max(0, end.getTime() - start.getTime());
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24)) || 30;
}

/**
 * Maps raw API suggestion items from the backend solver into the UI plan model.
 */
function mapApiSuggestions(
  rawList: ApiOptimizationSuggestion[],
  input: AISuggestionInput
): AISuggestionPlan[] {
  const baseStart =
    input.experiment.expectStartDate || new Date().toISOString().split("T")[0];
  const baseEnd = input.experiment.expectEndDate || baseStart;
  const totalDays = calculateDiffDays(baseStart, baseEnd);
  const formattedStart = formatDateShort(baseStart);
  const formattedEnd = formatDateShort(baseEnd);

  return rawList.map((item, idx) => {
    const rank = Number(item.rank ?? idx + 1);
    const isTop = rank === 1;
    const fitness = Number(item.fitnessScore ?? 0);
    const penaltyScore = Number(item.penaltyScore ?? 0);
    const bonusScore = Number(item.bonusScore ?? 0);
    const conflictCount = Number(item.conflictCount ?? 0);

    const timeline = Array.isArray(item.timeline) ? item.timeline : [];
    const allocatedLands = Array.isArray(item.allocatedLands)
      ? item.allocatedLands
      : [];
    const allocatedHumans = Array.isArray(item.allocatedHumans)
      ? item.allocatedHumans
      : [];
    const allocatedEquipment = Array.isArray(item.allocatedEquipment)
      ? item.allocatedEquipment
      : [];

    const durationDays = timeline.reduce(
      (max, t) => Math.max(max, Number(t.durationDays ?? 0)),
      totalDays
    );

    const firstStart = timeline[0]?.startDate
      ? formatDateShort(timeline[0].startDate)
      : formattedStart;
    const lastEnd = timeline[timeline.length - 1]?.endDate
      ? formatDateShort(timeline[timeline.length - 1].endDate)
      : formattedEnd;

    const advantages = Array.isArray(item.advantages) ? item.advantages : [];
    const disadvantages = Array.isArray(item.disadvantages)
      ? item.disadvantages
      : [];

    const rationale = [
      ...advantages,
      ...disadvantages.map((d) => (d.startsWith("Notice:") ? d : `Notice: ${d}`)),
    ];

    if (rationale.length === 0) {
      rationale.push(
        `Optimization plan generated by solver with fitness score of ${fitness.toFixed(1)}%.`
      );
    }

    const description =
      advantages.length > 0
        ? advantages.join(". ")
        : `AI optimization plan with fitness score of ${fitness.toFixed(1)}%.`;

    const changesSummary = [
      {
        field: "Timeline",
        from: `${totalDays} Days (${formattedStart} → ${formattedEnd})`,
        to: `${durationDays} Days (${firstStart} → ${lastEnd})`,
      },
      {
        field: "Equipment Allocation",
        from: `${input.equipmentRequirements?.length || 0} types requested`,
        to:
          allocatedEquipment.length > 0
            ? allocatedEquipment
                .map((e) => e.assetCode || e.equipmentTypeName || "Equipment")
                .join(", ")
            : "Standard availability",
      },
      {
        field: "Human Allocation",
        from: `${input.humanRequirements?.length || 0} roles requested`,
        to:
          allocatedHumans.length > 0
            ? allocatedHumans
                .map((h) => h.fullName || h.roleName || "Staff")
                .join(", ")
            : "Standard assignment",
      },
      {
        field: "Land Allocation",
        from: `${input.landRequirements?.length || 0} plot(s) requested`,
        to:
          allocatedLands.length > 0
            ? allocatedLands
                .map((l) => `${l.landCode || "Plot"} (${l.areaSize || 0} m²)`)
                .join(", ")
            : "Standard plot",
      },
    ];

    const experimentPhases =
      timeline.length > 0
        ? timeline.map((t, pIdx) => ({
            phaseName: t.phaseName || `Phase ${pIdx + 1}`,
            phaseDescription: `Optimized execution window (${t.durationDays || 0} days)`,
            phaseOrder: pIdx + 1,
            expectedStartDate: formatDateShort(t.startDate || baseStart),
            expectedEndDate: formatDateShort(t.endDate || baseEnd),
            status: "Planned" as const,
          }))
        : (input.experimentPhases || []).map((p, pIdx) => ({
            phaseName: p.phaseName,
            phaseDescription: p.phaseDescription || null,
            phaseOrder: p.phaseOrder || pIdx + 1,
            expectedStartDate: formatDateShort(p.expectedStartDate || baseStart),
            expectedEndDate: formatDateShort(p.expectedEndDate || baseEnd),
            status: "Planned" as const,
          }));

    const equipmentRequirements =
      allocatedEquipment.length > 0
        ? allocatedEquipment.map((e) => ({
            equipmentTypeId: Number(
              e.allocatedEquipmentTypeId || e.requiredEquipmentTypeId || 0
            ),
            equipmentTypeName:
              e.equipmentTypeName || e.assetCode || "Equipment",
            quantity: 1,
            allowSubstitute: Boolean(e.isSubstitute),
            minAcceptableEfficiency: Math.round(
              Number(e.efficiencyRate ?? 1) * 100
            ),
            note: e.assetCode ? `Assigned unit: ${e.assetCode}` : undefined,
          }))
        : (input.equipmentRequirements || []).map((e) => ({
            equipmentTypeId: e.equipmentTypeId,
            equipmentTypeName: e.equipmentTypeName,
            quantity: e.quantity,
            allowSubstitute: e.allowSubstitute,
            minAcceptableEfficiency: e.minAcceptableEfficiency,
            note: e.note,
          }));

    const humanRequirements =
      allocatedHumans.length > 0
        ? allocatedHumans.map((h) => ({
            roleId: Number(h.roleId || 0),
            roleName: h.fullName || h.roleName || "Personnel",
            quantity: 1,
            requiredSkillId: null,
            requiredSkillName: undefined,
            workingHoursPerDay: 8,
            note: h.fullName ? `Assigned staff: ${h.fullName}` : null,
          }))
        : (input.humanRequirements || []).map((h) => ({
            roleId: h.roleId,
            roleName: h.roleName,
            quantity: h.quantity,
            requiredSkillId: h.requiredSkillId,
            requiredSkillName: h.requiredSkillName,
            workingHoursPerDay: h.workingHoursPerDay,
            note: h.note,
          }));

    const landRequirements =
      allocatedLands.length > 0
        ? allocatedLands.map((l) => ({
            requiredArea: Number(l.areaSize || 0),
            requiredSoilType: l.soilType || null,
            note: l.landCode ? `Assigned plot: ${l.landCode}` : null,
          }))
        : (input.landRequirements || []).map((l) => ({
            requiredArea: l.requiredArea,
            requiredSoilType: l.requiredSoilType,
            note: l.note,
          }));

    return {
      id: `ai-plan-${rank}`,
      rank,
      title: isTop
        ? `Optimal Allocation Candidate (Rank #${rank})`
        : `Alternative Candidate (Rank #${rank})`,
      strategyBadge: isTop
        ? "Recommended (Rank 1)"
        : `Rank #${rank} • Fitness ${fitness.toFixed(1)}%`,
      description,
      fitnessScore: fitness,
      penaltyScore,
      bonusScore,
      fitnessBreakdown: item.fitnessBreakdown,
      constraintReport: item.constraintReport,
      conflictCount,
      estimatedCompletionTime: item.estimatedCompletionTime,
      estimatedDurationDays: durationDays,
      totalResourceScore: Math.round(fitness),
      advantages,
      disadvantages,
      rationale,
      changesSummary,
      allocatedLands,
      allocatedHumans,
      allocatedEquipment,
      timeline,
      experimentPhases,
      equipmentRequirements,
      humanRequirements,
      landRequirements,
    };
  });
}

/**
 * Service function to fetch real AI experiment plan suggestions from the backend optimization API.
 * Calls POST /api/AllocationOptimizations/experiments/{experimentId}/suggestions
 */
export async function generateAISuggestions(
  input: AISuggestionInput,
  settings: OptimizationSettings = {}
): Promise<AISuggestionResponse> {
  const experimentId = input.experiment.experimentId;

  if (!experimentId || experimentId <= 0) {
    throw new Error("Experiment ID is required to generate AI suggestions.");
  }

  const mergedSettings: OptimizationSettings = {
    ...DEFAULT_OPTIMIZATION_SETTINGS,
    ...settings,
  };

  const response = await api.post(
    `/AllocationOptimizations/experiments/${experimentId}/suggestions`,
    mergedSettings
  );

  const rawData = response.data?.data ?? response.data;
  const rawList: ApiOptimizationSuggestion[] = Array.isArray(rawData)
    ? rawData
    : [];

  if (rawList.length === 0) {
    throw new Error("No AI suggestions were returned by the optimization solver.");
  }

  const suggestions = mapApiSuggestions(rawList, input);
  return { suggestions };
}
